### PR TITLE
fixing deploy to azure buttons-pim/fixing directory structure 

### PR DESCRIPTION
**Pull request by olsenme**
Hi everyone, 
-Fixing all of the PIM-related templates to fix the deploy to azure buttons
-changed ".Parameters" to lowercase on "subscription.parameters" under pim templates
-moved "rg-delegated-resource-management" templates underneath "delegated-resource-management" with sub and rg folders

### CODE REVIEW

**Comment by skayani** [comment]
Due to the renamed/moved files, do any references in the README have to be updated?

**Comment by olsenme** [comment]
yes @skayani . I will update

**Comment by olsenme** [comment]
but it has to get merged first

**Comment by olsenme** [comment]
Once you merge in, I will use the raw JSON to re-generate the uris for the 3 buttons affected

**Comment by serenaz** [comment]
Thanks both for reviewing.

**Pull request merged**
